# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The dantou's blog 
email: 454713468@qq.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to the dantou's blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.dantou.cc"
github_username: dantougit 
tagline: A newbie named dantou! 
# Build settings
markdown: kramdown
